name: device_display_brightness
description: A Flutter plugin to manage the device's display brightness on Android and iOS.
version: 1.0.0
homepage: https://github.com/jaylane/device_display_brightness

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jlane.device_display_brightness
        pluginClass: DeviceDisplayBrightnessPlugin
      ios:
        pluginClass: DeviceDisplayBrightnessPlugin
